blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path('', views.ArticleList.as_view(), name='home'),
    path('page/<int:page>', views.ArticleList.as_view(), name='home'),
    path('article/<slug:slug>', views.ArticleDetail.as_view(), name="detail"),
    path('preview/<int:pk>', views.ArticlePreview.as_view(), name="preview"),
    path('category/<slug:slug>', views.CategoryList.as_view(), name="category"),
    path('category/<slug:slug>/page/<int:page>',
         views.CategoryList.as_view(), name="category"),
    path('author/<slug:username>',
         views.AuthorList.as_view(), name="author"),
    path('author/<slug:username>/page/<int:page>',
         views.AuthorList.as_view(), name="author"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

from account.views import Login, Register, activate

urlpatterns = [
    path('', include('blog.urls')),
    path('', include('django.contrib.auth.urls')),
    path('login/', Login.as_view(), name='login'),
    path('register/', Register.as_view(), name='register'),
    path('activate/(<uidb64>/(<token>/', activate, name='activate'),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
    path('comment/', include('comment.urls')),

] 

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from ipaddress import ip_address
from account.models import User
from django.db import models
from django.utils.html import format_html
from django.utils import timezone
from django.urls import reverse
from django.contrib.contenttypes.fields import GenericRelation

from comment.models import Comment

from extensions.utils import jalali_converter

# my managers
class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status='p')


class CategoryManager(models.Manager):
    def active(self):
        return self.filter(status=True)

# Models
class IP(models.Model):
    ip_address = models.GenericIPAddressField(verbose_name="آدرس آی-پی")


class Article(models.Model):

    STATUS_CHOICES = (
        ('d', 'پیش نویس'),
        ('p', 'منتشر شده'),
        ('i', 'در حال بررسی'),
        ('b', 'برگشت خورده'),
    )
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='articles', verbose_name='نویسنده')
    title = models.CharField(max_length=128, verbose_name="عنوان")
    category = models.ManyToManyField(
        'Category', verbose_name="دسته بندی", related_name="articles")
    description = models.TextField(verbose_name="توضیحات")
    img = models.ImageField(upload_to="Images", verbose_name="عکس")
    publish = models.DateTimeField(
        default=timezone.now, verbose_name="زمان انتشار")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    is_special = models.BooleanField(default=False, verbose_name="مقاله ویژه")
    status = models.CharField(
        max_length=1, choices=STATUS_CHOICES, verbose_name="وضعیت")
    slug = models.SlugField(max_length=100, unique=True, verbose_name="آدرس")
    comments = GenericRelation(Comment)
    hits = models.ManyToManyField(IP, through='ArticleHit', blank=True, related_name="hits", verbose_name="بازدید ها")

    class Meta:
        verbose_name = "مقاله"
        verbose_name_plural = "مقاله ها"

    def __str__(self):
        return self.title

    def jpublish(self):
        return jalali_converter(self.publish)
    jpublish.short_description = "زمان انتشار"

    def thumbnail_tag(self):
        return format_html("<img width='60' height='60' style='border-radius: 5px;' src='{}'>".format(self.img.url))
    thumbnail_tag.short_description = "عکس"
    
    def category_to_str(self):
        return "، ".join([category.title for category in self.category.active()])
    category_to_str.short_description = "دسته بندی"

    def get_absolute_url(self):
        return reverse("account:home")


    objects = models.Manager()
    published_objects = ArticleManager()


class ArticleHit(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    ip_address = models.ForeignKey(IP, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)


class Category(models.Model):
    parent = models.ForeignKey('self', default=None, null=True, blank=True, on_delete=models.SET_NULL, related_name='children', verbose_name='زیر دسته')
    title = models.CharField(max_length=200, verbose_name="عنوان دسته بندی")
    slug = models.SlugField(max_length=100, unique=True,
                            verbose_name="آدرس دسته بندی")
    status = models.BooleanField(default=True, verbose_name="وضعیت نمایش")
    position = models.IntegerField(verbose_name="موقعیت")

    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها"
        ordering = ['parent__id', 'position']

    def __str__(self):
        return self.title

    objects = CategoryManager()

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, JsonResponse, Http404
from django.core.paginator import Paginator
from django.views.generic import ListView, DetailView
from django.db.models import Count, Q
from datetime import datetime, timedelta

from account.models import User
from .models import Article, Category, ArticleHit
from account.mixins import AuthorAccessMixin


class ArticleList(ListView):
    queryset = Article.published_objects.published()
    template_name = "blog/home.html"
    context_object_name = "articles"
    paginate_by = 4
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        last_month = datetime.today() - timedelta(days=30)
        context['popular_articles'] = Article.published_objects.published().annotate(
            count=Count('hits', filter=Q(articlehit__created__gt=last_month))
            ).order_by('-count', '-publish')[:5]
        return context



class ArticleDetail(DetailView):
    def get_object(self):
        slug = self.kwargs.get('slug')
        article =  get_object_or_404(Article.published_objects.published(), slug=slug)
        
        ip_address = self.request.user.ip_address
        if ip_address not in article.hits.all():
            article.hits.add(ip_address)

        return article
    template_name = "blog/detail.html"


class ArticlePreview(AuthorAccessMixin, DetailView):
    def get_object(self):
        pk = self.kwargs.get('pk')
        return get_object_or_404(Article, pk=pk)
    template_name = "blog/detail.html"


class CategoryList(ListView):
    paginate_by = 4
    template_name = "blog/category.html"
    context_object_name = "articles"

    def get_queryset(self):
        global category
        slug = self.kwargs.get('slug')
        category = get_object_or_404(Category.objects.active(), slug=slug)
        return Article.published_objects.published().filter(category=category)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = category
        return context


class AuthorList(ListView):
    paginate_by = 2
    template_name = "blog/author_list.html"
    context_object_name = "articles"

    def get_queryset(self):
        global author
        username = self.kwargs.get('username')
        author = get_object_or_404(User, username=username)
        return Article.published_objects.published().filter(author=author)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = author
        return context

comment/views/base.py
from django.views.generic import FormView

from comment.conf import settings
from comment.context import DABContext
from comment.responses import DABResponseData
from comment.messages import EmailInfo
from comment.service.email import DABEmailService
from comment.forms import CommentForm


class BaseCommentView(FormView, DABResponseData):
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = context.pop('form')
        context.update(DABContext(self.request))
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


class CommentCreateMixin(BaseCommentView):
    email_service = None

    def _initialize_email_service(self, comment, request):
        self.email_service = DABEmailService(comment, request)

    def _send_notification_to_followers(self, comment, request):
        if settings.COMMENT_ALLOW_SUBSCRIPTION:
            self._initialize_email_service(comment, request)
            self.email_service.send_notification_to_followers()

    def perform_save(self, comment, request):
        comment.save()
        self._send_notification_to_followers(comment, request)
        comment.refresh_from_db()
        return comment

    def _handle_anonymous(self, comment, request, api=False):
        self._initialize_email_service(comment, request)
        self.email_service.send_confirmation_request(api=api)
        self.anonymous = True
        self.msg = EmailInfo.CONFIRMATION_SENT

    def perform_create(self, comment, request, api=False):
        if settings.COMMENT_ALLOW_ANONYMOUS and not comment.user:
            self._handle_anonymous(comment, request, api)
        else:
            comment = self.perform_save(comment, request)
        return comment

blog/templates/blog/about.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">Sample Post</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/about-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>About Me</h1>
                            <span class="subheading">This is what I do.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
                    </div>
                </div>
            </div>
        </main>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2021</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

blog/templates/blog/author_list.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}سلیسیوم{% endblock title %}
<!-- Page Header-->
{% block content %}
<header class="masthead" style="background-image:url('{% static 'blog/assets/img/home-bg.jpg' %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>سیلیسیوم</h1>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Main Content-->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <h3 class="alert alert-primary text-center">نویسنده: {{ author.get_full_name }}</h3>
            {% for article in articles %}
            <!-- Post preview-->
            <div class="post-preview">
                <a href="{% url 'blog:detail' article.slug %}">
                    <h2 class="post-title">
                        {{ article.title }}
                    </h2>
                </a>
                <h3 class="post-subtitle">
                    {{ article.description|truncatewords:4 }}
                </h3>
                <p class="post-meta">
                    انتشار شده توسط
                    <a href="{% url 'blog:author' article.author %}"> {{ article.author.get_full_name }} </a>
                    {{ article.jpublish }}
                </p>
                <div>
                    {% for cat in article.category.active %}
                    <a href="{% url 'blog:category' cat.slug %}"># {{ cat.title }}</a>

                    {% endfor %}
                </div>
            </div>
            <!-- Divider-->
            <hr class="my-4" />
            {% endfor %}
            <!-- Pager-->
            <div class="clearfix pager-bottun">
                {% if page_obj.has_previous %}
                <a class="btn btn-primary float-right ml-3"
                    href="{% url 'blog:author' author.username page_obj.previous_page_number %}">پست های جدید تر
                    &rarr;</a>
                {% endif %}
                {% if page_obj.has_next %}
                <a class="btn btn-primary float-left"
                    href="{% url 'blog:author' author.username  page_obj.next_page_number %}">پست
                    های
                    قدیمی تر &larr;</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endblock content %}

blog/templates/blog/base.html
{% load static %}
{% load base_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>{% block title %}base{% endblock title %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'blog/assets/favicon.ico' %}" />
    <link rel="stylesheet" href="{% static 'blog/css/styles.css' %}">
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet"
        type="text/css" />
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
        rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="css/styles.css" rel="stylesheet">
    <link href="{% static 'blog/css/rtl.css' %}" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
    <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
    
...
</head>

<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="{% url 'blog:home' %}">{% title %}</a>
            {% if not user.is_authenticated %}
                <a class="navbar-brand" href="{% url 'login' %}">ورود</a>
            {% else %}
                <a class="navbar-brand" href="{% url 'logout' %}">خروج از اکانت کاربری</a>
            {% endif %}
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            {% category_navbar %}
        </div>
    </nav>
    {% block content %}

    {% endblock content %}
    <!-- Footer-->
    <footer class="border-top">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <ul class="list-inline text-center">
                        <li class="list-inline-item">
                            <a href="#!">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#!">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#!">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <div class="small text-center text-muted fst-italic">Copyright &copy; my website 2022</div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="js/scripts.js"></script>
</body>

</html>

blog/templates/blog/category.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}سلیسیوم{% endblock title %}
<!-- Page Header-->
{% block content %}
<header class="masthead" style="background-image:url('{% static 'blog/assets/img/home-bg.jpg' %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>سیلیسیوم</h1>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Main Content-->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <h3 class="alert alert-primary text-center">دسته بندی: {{ category.title }}</h3>
            {% for article in articles %}
            <!-- Post preview-->
            <div class="post-preview">
                <a href="{% url 'blog:detail' article.slug %}">
                    <h2 class="post-title">
                        {{ article.title }}
                    </h2>
                </a>
                <h3 class="post-subtitle">
                    {{ article.description|truncatewords:4 }}
                </h3>
                <p class="post-meta">
                    انتشار شده توسط
                    <a href="#!"> امیرو </a>
                    {{ article.jpublish }}
                </p>
                <div>
                    {% for cat in article.category.active %}
                    <a href="{% url 'blog:category' cat.slug %}"># {{ cat.title }}</a>

                    {% endfor %}
                </div>
            </div>
            <!-- Divider-->
            <hr class="my-4" />
            {% endfor %}
            <!-- Pager-->
            <div class="clearfix pager-bottun">
                {% if page_obj.has_previous %}
                <a class="btn btn-primary float-right ml-3"
                    href="{% url 'blog:category' category.slug page_obj.previous_page_number %}">پست های جدید تر
                    &rarr;</a>
                {% endif %}
                {% if page_obj.has_next %}
                <a class="btn btn-primary float-left"
                    href="{% url 'blog:category' category.slug  page_obj.next_page_number %}">پست
                    های
                    قدیمی تر &larr;</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endblock content %}

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% load comment_tags %}
{% load static %}
{% load ratings %}

{% block title %} سلیسیوم| {{ article.title }}{% endblock title %}

{% block content %}
<!-- Page Header-->
<header class="masthead" style="background-image: url('{{ article.img.url }}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>{{ article.title }}</h1>
                    {% if article.is_special %}
                            <span class="badge badge-danger">ویژه</span>
                            <i class="fa fa-check-circle" style="color: gold"></i>
                    {% endif %}
                    <span class="meta">
                        <p class="post-meta">
                            انتشار شده توسط
                            <a href="{% url 'blog:author' article.author %}"> {{ article.author.get_full_name }} </a>
                        </p>
                        <time>{{ article.jpublish }}</time></small>
                        <div>{% ratings object %}</div>
                        <div>بازدید ها:{{ article.hits.count }}</div>
                    </span>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Post Content-->
<article class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7 text-justify">
            {% if object.is_special %}
                {% if user.is_authenticated and user.is_special_user or user == object.author or user.is_superuser %}
                    {{ article.description|safe }}
                {% else %}
                    {{ article.description|striptags|truncatewords:7 }}
                    <p class="alert alert-warning"> برای مشاهده این مقاله باید <a href="#"> اشتراک ویژه </a>تهیه کنید.</p>
                {% endif %}
            {% else %}
                {{ article.description|safe }}
            {% endif %}
            
            {% render_comments article request %}
            {% include_bootstrap %} 
            </div>
        </div>
    </div>
</article>
{% endblock content %}

blog/templates/blog/home.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}سلیسیوم{% endblock title %}
<!-- Page Header-->
{% block content %}
<header class="masthead" style="background-image:url('{% static 'blog/assets/img/home-bg.jpg' %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>سیلیسیوم</h1>
                </div>
            </div>
        </div>
    </div>
    
</header>
<!-- Main Content-->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <div class="popular_articles">
                <h2 class="h4">مقالات پر بازدید ماه</h2>
                <hr>
                {% for a in popular_articles %}
                    <div>
                        <a href="{% url 'blog:detail' a.slug %}">{{ a.title }}</a>
                    </div>
                {% endfor %}
            </div>
            {% for article in articles %}
            <!-- Post preview-->
            <div class="post-preview">
                <a href="{% url 'blog:detail' article.slug %}">
                    <h2 class="post-title">
                        {{ article.title }}
                        {% if article.is_special %}
                            <!-- <span class="badge badge-primary"> "ویژه" </span> -->
                            <i class="fa fa-check-circle" style="color: gold"></i>
                        {% endif %}
                    </h2>
                </a>
                <h3 class="post-subtitle">
                    {{ article.description|striptags|truncatewords:4 }}
                </h3>
                <p class="post-meta">
                    انتشار شده توسط
                    <a href="{% url 'blog:author' article.author %}"> {{ article.author.get_full_name }} </a>
                    {{ article.jpublish }}
                </p>
                <div>
                    {% for cat in article.category.active %}
                    <a href="{% url 'blog:category' cat.slug %}"># {{ cat.title }}</a>

                    {% endfor %}
                </div>
                <div>بازدید ها: {{ article.hits.count }}</div>
            </div>
            <!-- Divider-->
            <hr class=" my-4" />
            {% endfor %}
            <!-- Pager-->
            <div class="clearfix pager-bottun">
                {% if page_obj.has_previous %}
                <a class="btn btn-primary float-right ml-3"
                    href="{% url 'blog:home' page_obj.previous_page_number %}">پست های جدید تر &rarr;</a>
                {% endif %}
                {% if page_obj.has_next %}
                <a class="btn btn-primary float-left" href="{% url 'blog:home' page_obj.next_page_number %}">پست
                    های
                    قدیمی تر &larr;</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
</div>
{% endblock content %}